#!/bin/bash
# ================================================================
#   SAIMUM v3.0 — report.sh — Stage 9: Reporting
# ================================================================

generate_txt_report() {
    local target="$1"
    local rfile="$OUTPUT_DIR/${REPORT_FILENAME}.txt"

    {
        echo "================================================================"
        echo "   SAIMUM v3.0 — PENTEST REPORT"
        echo "================================================================"
        echo "Target      : $target"
        echo "Scan Date   : $(date)"
        echo "Scan Mode   : $([ "$SCAN_MODE" -eq 1 ] && echo 'Stealth' || ([ "$SCAN_MODE" -eq 2 ] && echo 'Normal' || echo 'Aggressive'))"
        echo "Duration    : $(elapsed_total)"
        echo "Output Dir  : $OUTPUT_DIR"
        echo ""
        echo "================================================================"
        echo "   EXECUTIVE SUMMARY"
        echo "================================================================"
        echo "🔴 Critical : $COUNT_CRITICAL"
        echo "🟠 High     : $COUNT_HIGH"
        echo "🟡 Medium   : $COUNT_MEDIUM"
        echo "🟢 Low      : $COUNT_LOW"
        echo "🔵 Info     : $COUNT_INFO"
        local total=$(( COUNT_CRITICAL + COUNT_HIGH + COUNT_MEDIUM + COUNT_LOW ))
        echo ""
        echo "Total Findings: $total"
        echo ""

        # Risk Rating
        if [ "$COUNT_CRITICAL" -gt 0 ]; then
            echo "⚠️  OVERALL RISK: 🔴 CRITICAL — অবিলম্বে remediation প্রয়োজন!"
        elif [ "$COUNT_HIGH" -gt 0 ]; then
            echo "⚠️  OVERALL RISK: 🟠 HIGH"
        elif [ "$COUNT_MEDIUM" -gt 0 ]; then
            echo "⚠️  OVERALL RISK: 🟡 MEDIUM"
        else
            echo "✅ OVERALL RISK: 🟢 LOW / INFO"
        fi

        echo ""
        echo "================================================================"
        echo "   TARGET INFORMATION"
        echo "================================================================"
        echo "IP Address  : ${TARGET_IP:-N/A}"
        echo "Domain      : ${TARGET_DOMAIN:-N/A}"
        echo "CMS         : ${DETECTED_CMS:-Not detected}"
        echo "Framework   : ${DETECTED_FRAMEWORK:-Not detected}"
        echo "CDN         : $([ "$HAS_CDN" -eq 1 ] && echo "$CDN_NAME" || echo 'None detected')"
        echo "WAF         : $([ "$HAS_WAF" -eq 1 ] && echo "$WAF_NAME" || echo 'None detected')"
        echo ""
        echo "Open Ports  : ${OPEN_PORTS[*]:-None}"
        echo "Subdomains  : ${#FOUND_SUBDOMAINS[@]} found"
        echo "Emails      : ${#FOUND_EMAILS[@]} found"
        echo "Live Hosts  : ${#LIVE_SUBDOMAINS[@]} found"
        echo ""

        echo "================================================================"
        echo "   DETAILED FINDINGS"
        echo "================================================================"
        echo ""

        # Concat all bangla analysis files
        for f in "$OUTPUT_DIR"/*_bangla.txt; do
            [ -f "$f" ] && { cat "$f"; echo ""; }
        done

        echo ""
        echo "================================================================"
        echo "   CVE REFERENCES"
        echo "================================================================"
        grep -roh "CVE-[0-9]\+-[0-9]\+" "$OUTPUT_DIR"/*.txt 2>/dev/null | \
            sort -u | while read -r cve; do
            echo "  $cve → https://nvd.nist.gov/vuln/detail/$cve"
        done

        echo ""
        echo "================================================================"
        echo "   TOOL TIMELINE"
        echo "================================================================"
        for tool in "${!TOOL_DURATIONS[@]}"; do
            local d="${TOOL_DURATIONS[$tool]}"
            printf "  %-35s %dm %ds\n" "$tool" "$((d/60))" "$((d%60))"
        done

        echo ""
        echo "   Tools Used    : ${#TOOLS_USED[@]}"
        echo "   Tools Skipped : ${#TOOLS_SKIPPED[@]}"
        echo "   Skipped       : ${TOOLS_SKIPPED[*]:-none}"

        echo ""
        echo "================================================================"
        echo "   REMEDIATION PRIORITIES"
        echo "================================================================"
        local prio=1
        grep -rh "CRITICAL:" "$OUTPUT_DIR"/*_bangla.txt 2>/dev/null | \
            grep -v "^=\|^$" | head -10 | while read -r l; do
            echo "  [$prio] 🔴 $l"; ((prio++))
        done
        grep -rh "HIGH:" "$OUTPUT_DIR"/*_bangla.txt 2>/dev/null | \
            grep -v "^=\|^$" | head -10 | while read -r l; do
            echo "  [$prio] 🟠 $l"; ((prio++))
        done

        echo ""
        echo "================================================================"
        echo "   Report generated by SAIMUM v3.0"
        echo "   For educational and authorized testing purposes only."
        echo "================================================================"
    } | tee "$rfile"

    log_success "TXT Report → $rfile"
    reg_file "report_txt" "$rfile"
}

generate_html_report() {
    local target="$1"
    local rfile="$OUTPUT_DIR/${REPORT_FILENAME}.html"

    # Screenshot embed helper
    local ss_html=""
    if [ -d "$OUTPUT_DIR/screenshots" ]; then
        ss_html="<h2>📸 Screenshots</h2><div class='ss-grid'>"
        for img in "$OUTPUT_DIR/screenshots"/*.png; do
            [ -f "$img" ] && {
                local b64; b64=$(base64 -w0 "$img" 2>/dev/null)
                local nm; nm=$(basename "$img")
                ss_html+="<div class='ss-item'><img src='data:image/png;base64,$b64'/><p>$nm</p></div>"
            }
        done
        ss_html+="</div>"
    fi

    # Findings table rows
    local cve_rows=""
    while IFS= read -r cve; do
        cve_rows+="<tr><td><a href='https://nvd.nist.gov/vuln/detail/$cve' target='_blank'>$cve</a></td></tr>"
    done < <(grep -roh "CVE-[0-9]\+-[0-9]\+" "$OUTPUT_DIR"/*.txt 2>/dev/null | sort -u)

    cat > "$rfile" << HTMLEOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>SAIMUM v3.0 — Pentest Report: $target</title>
<style>
  :root{--bg:#0d1117;--bg2:#161b22;--bg3:#21262d;--border:#30363d;
        --green:#3fb950;--red:#f85149;--orange:#d29922;--yellow:#e3b341;
        --blue:#58a6ff;--purple:#bc8cff;--text:#c9d1d9;--dim:#8b949e}
  *{box-sizing:border-box;margin:0;padding:0}
  body{background:var(--bg);color:var(--text);font-family:'Segoe UI',monospace;font-size:14px}
  .container{max-width:1200px;margin:0 auto;padding:20px}
  h1{color:var(--blue);font-size:2em;text-align:center;margin:20px 0;
     text-shadow:0 0 20px var(--blue)}
  h2{color:var(--purple);margin:24px 0 12px;border-bottom:1px solid var(--border);padding-bottom:8px}
  h3{color:var(--blue);margin:16px 0 8px}
  .badge{display:inline-block;padding:2px 8px;border-radius:4px;
         font-size:12px;font-weight:bold;margin:2px}
  .critical{background:#3d0000;color:var(--red);border:1px solid var(--red)}
  .high{background:#2d1a00;color:var(--orange);border:1px solid var(--orange)}
  .medium{background:#2d2200;color:var(--yellow);border:1px solid var(--yellow)}
  .low{background:#0d2a0d;color:var(--green);border:1px solid var(--green)}
  .info{background:#0d1a2d;color:var(--blue);border:1px solid var(--blue)}
  .card{background:var(--bg2);border:1px solid var(--border);border-radius:8px;
        padding:16px;margin:12px 0}
  .summary-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:16px 0}
  .summary-card{background:var(--bg3);border-radius:8px;padding:16px;text-align:center;
                border:1px solid var(--border)}
  .summary-card .num{font-size:2.5em;font-weight:bold}
  .summary-card .lbl{font-size:12px;color:var(--dim)}
  .info-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
  .kv{display:flex;gap:8px;padding:4px 0;border-bottom:1px solid var(--border)}
  .kv .k{color:var(--dim);min-width:120px}
  .kv .v{color:var(--text)}
  pre{background:var(--bg3);padding:12px;border-radius:6px;overflow-x:auto;
      font-size:12px;line-height:1.5;white-space:pre-wrap;word-break:break-all}
  table{width:100%;border-collapse:collapse}
  th,td{padding:8px 12px;border:1px solid var(--border);text-align:left}
  th{background:var(--bg3);color:var(--blue)}
  tr:nth-child(even){background:var(--bg2)}
  .timeline{display:flex;flex-direction:column;gap:4px}
  .tl-item{display:flex;gap:12px;padding:6px;background:var(--bg3);
           border-radius:4px;border-left:3px solid var(--blue)}
  .ss-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:12px}
  .ss-item{text-align:center;background:var(--bg3);padding:8px;border-radius:6px}
  .ss-item img{width:100%;height:120px;object-fit:cover;border-radius:4px}
  .ss-item p{font-size:11px;color:var(--dim);margin-top:4px}
  a{color:var(--blue);text-decoration:none}
  a:hover{text-decoration:underline}
  .risk-critical{color:var(--red);font-size:1.2em;font-weight:bold}
  .risk-high{color:var(--orange);font-size:1.2em;font-weight:bold}
  .risk-medium{color:var(--yellow);font-size:1.2em;font-weight:bold}
  .risk-low{color:var(--green);font-size:1.2em;font-weight:bold}
  .nav{position:sticky;top:0;background:var(--bg2);border-bottom:1px solid var(--border);
       padding:8px 20px;display:flex;gap:16px;z-index:100;overflow-x:auto}
  .nav a{color:var(--dim);font-size:13px;white-space:nowrap}
  .nav a:hover{color:var(--text)}
  @media(max-width:600px){.summary-grid{grid-template-columns:repeat(3,1fr)};
                          .info-grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="nav">
  <a href="#summary">Summary</a>
  <a href="#target">Target</a>
  <a href="#findings">Findings</a>
  <a href="#cve">CVE</a>
  <a href="#timeline">Timeline</a>
  $([ -n "$ss_html" ] && echo '<a href="#screenshots">Screenshots</a>')
</div>
<div class="container">
  <h1>🔐 SAIMUM v3.0 — Pentest Report</h1>
  <p style="text-align:center;color:var(--dim)">Target: <strong style="color:var(--blue)">$target</strong> | $(date) | Mode: $([ "$SCAN_MODE" -eq 1 ] && echo 'Stealth' || ([ "$SCAN_MODE" -eq 2 ] && echo 'Normal' || echo 'Aggressive')) | Duration: $(elapsed_total)</p>

  <div id="summary">
  <h2>📊 Executive Summary</h2>
  <div class="summary-grid">
    <div class="summary-card"><div class="num" style="color:var(--red)">$COUNT_CRITICAL</div><div class="lbl">CRITICAL</div></div>
    <div class="summary-card"><div class="num" style="color:var(--orange)">$COUNT_HIGH</div><div class="lbl">HIGH</div></div>
    <div class="summary-card"><div class="num" style="color:var(--yellow)">$COUNT_MEDIUM</div><div class="lbl">MEDIUM</div></div>
    <div class="summary-card"><div class="num" style="color:var(--green)">$COUNT_LOW</div><div class="lbl">LOW</div></div>
    <div class="summary-card"><div class="num" style="color:var(--blue)">$COUNT_INFO</div><div class="lbl">INFO</div></div>
  </div>
  </div>

  <div id="target">
  <h2>🎯 Target Information</h2>
  <div class="info-grid">
    <div class="card">
      <div class="kv"><span class="k">IP Address</span><span class="v">${TARGET_IP:-N/A}</span></div>
      <div class="kv"><span class="k">Domain</span><span class="v">${TARGET_DOMAIN:-N/A}</span></div>
      <div class="kv"><span class="k">CMS</span><span class="v">${DETECTED_CMS:-Not detected}</span></div>
      <div class="kv"><span class="k">Framework</span><span class="v">${DETECTED_FRAMEWORK:-Not detected}</span></div>
    </div>
    <div class="card">
      <div class="kv"><span class="k">CDN</span><span class="v">$([ "$HAS_CDN" -eq 1 ] && echo "$CDN_NAME" || echo 'None')</span></div>
      <div class="kv"><span class="k">WAF</span><span class="v">$([ "$HAS_WAF" -eq 1 ] && echo "$WAF_NAME" || echo 'None')</span></div>
      <div class="kv"><span class="k">Open Ports</span><span class="v">${OPEN_PORTS[*]:-None}</span></div>
      <div class="kv"><span class="k">Subdomains</span><span class="v">${#FOUND_SUBDOMAINS[@]}</span></div>
    </div>
  </div>
  </div>

  <div id="findings">
  <h2>🔍 Detailed Findings</h2>
HTMLEOF

    # Add each bangla analysis
    for f in "$OUTPUT_DIR"/*_bangla.txt; do
        [ -f "$f" ] || continue
        local fname; fname=$(basename "$f" _bangla.txt)
        local content; content=$(cat "$f" | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g')
        echo "  <div class='card'><h3>$fname</h3><pre>$content</pre></div>" >> "$rfile"
    done

    # CVE table
    cat >> "$rfile" << HTMLEOF2
  </div>

  <div id="cve">
  <h2>📌 CVE References</h2>
  <div class="card">
  <table>
    <tr><th>CVE ID</th></tr>
    $cve_rows
  </table>
  </div>
  </div>

  <div id="timeline">
  <h2>⏱️ Tool Timeline</h2>
  <div class="card timeline">
HTMLEOF2

    for tool in "${!TOOL_DURATIONS[@]}"; do
        local d="${TOOL_DURATIONS[$tool]}"
        echo "    <div class='tl-item'><span style='color:var(--blue);min-width:200px'>$tool</span><span>${d}s (${d}s)</span></div>" >> "$rfile"
    done

    cat >> "$rfile" << HTMLEOF3
  </div>
  </div>

  $ss_html

  <p style="text-align:center;color:var(--dim);margin-top:40px;padding-top:20px;
     border-top:1px solid var(--border)">
    Generated by <strong>SAIMUM v3.0</strong> — For authorized testing only.
  </p>
</div>
</body>
</html>
HTMLEOF3

    log_success "HTML Report → $rfile"
    reg_file "report_html" "$rfile"
}

generate_json_report() {
    local target="$1"
    local rfile="$OUTPUT_DIR/${REPORT_FILENAME}.json"

    # Write Python script to temp file to avoid heredoc/variable expansion issues
    local pyscript="/tmp/saimum_json_$$.py"
    cat > "$pyscript" << 'PYEOF'
import json, os, re, datetime, sys

output_dir = sys.argv[1]
target     = sys.argv[2]
scan_mode  = int(sys.argv[3])
summary    = json.loads(sys.argv[4])
tinfo      = json.loads(sys.argv[5])
tu         = sys.argv[6].split() if sys.argv[6] else []
ts         = sys.argv[7].split() if sys.argv[7] else []

findings = []
for f in sorted(os.listdir(output_dir)):
    if f.endswith('_bangla.txt'):
        tool = f.replace('_bangla.txt', '')
        try:
            with open(os.path.join(output_dir, f)) as fh:
                content = fh.read()
        except Exception:
            content = ''
        sev = 'info'
        if 'CRITICAL' in content: sev = 'critical'
        elif 'HIGH' in content:   sev = 'high'
        elif 'MEDIUM' in content: sev = 'medium'
        elif 'LOW' in content:    sev = 'low'
        findings.append({'tool': tool, 'severity': sev, 'content': content[:500]})

cves = set()
for f in os.listdir(output_dir):
    if f.endswith('.txt'):
        try:
            with open(os.path.join(output_dir, f)) as fh:
                cves.update(re.findall(r'CVE-\d+-\d+', fh.read()))
        except Exception:
            pass

report = {
    'tool': 'SAIMUM v3.0',
    'target': target,
    'scan_date': datetime.datetime.now().isoformat(),
    'scan_mode': scan_mode,
    'summary': summary,
    'target_info': tinfo,
    'cves': sorted(list(cves)),
    'findings': findings,
    'tools_used': tu,
    'tools_skipped': ts
}
print(json.dumps(report, indent=2))
PYEOF

    # Build JSON args safely
    local summary_json
    summary_json=$(printf '{"critical":%d,"high":%d,"medium":%d,"low":%d,"info":%d}' \
        "$COUNT_CRITICAL" "$COUNT_HIGH" "$COUNT_MEDIUM" "$COUNT_LOW" "$COUNT_INFO")
    local tinfo_json
    tinfo_json=$(printf '{"ip":"%s","domain":"%s","cms":"%s","cdn":"%s","waf":"%s"}' \
        "${TARGET_IP:-}" "${TARGET_DOMAIN:-}" "${DETECTED_CMS:-}" \
        "${CDN_NAME:-}" "${WAF_NAME:-}")

    python3 "$pyscript" \
        "$OUTPUT_DIR" "$target" "$SCAN_MODE" \
        "$summary_json" "$tinfo_json" \
        "${TOOLS_USED[*]:-}" "${TOOLS_SKIPPED[*]:-}" \
        > "$rfile" 2>/dev/null || \
        echo "{\"target\":\"$target\",\"critical\":$COUNT_CRITICAL}" > "$rfile"

    rm -f "$pyscript"
    log_success "JSON Report → $rfile"
    reg_file "report_json" "$rfile"
}

generate_pdf_report() {
    local target="$1"
    command -v wkhtmltopdf &>/dev/null || { log_skip "wkhtmltopdf (PDF)"; return; }
    local html="$OUTPUT_DIR/${REPORT_FILENAME}.html"
    [ ! -f "$html" ] && { log_warn "HTML নেই — PDF skip।"; return; }
    local rfile="$OUTPUT_DIR/${REPORT_FILENAME}.pdf"

    run_tool "wkhtmltopdf" \
        "wkhtmltopdf --page-size A4 --margin-top 10 --margin-bottom 10 \
         --margin-left 10 --margin-right 10 --encoding UTF-8 \
         --no-background --quiet $html $rfile" \
        "/dev/null" 60

    [ -f "$rfile" ] && log_success "PDF Report → $rfile"
    reg_file "report_pdf" "$rfile"
}

show_terminal_dashboard() {
    echo ""
    echo -e "${CYAN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${WHITE}${BOLD}   🏁 SAIMUM v3.0 — SCAN COMPLETE${NC}"
    echo -e "${CYAN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo -e "  Target   : ${BLUE}${BOLD}$CURRENT_TARGET${NC}"
    echo -e "  Duration : ${GREEN}$(elapsed_total)${NC}"
    echo ""
    echo -e "  ${WHITE}Findings:${NC}"
    echo -e "   🔴 Critical : ${RED}${BOLD}$COUNT_CRITICAL${NC}"
    echo -e "   🟠 High     : ${ORANGE}${BOLD}$COUNT_HIGH${NC}"
    echo -e "   🟡 Medium   : ${YELLOW}${BOLD}$COUNT_MEDIUM${NC}"
    echo -e "   🟢 Low      : ${GREEN}${BOLD}$COUNT_LOW${NC}"
    echo -e "   🔵 Info     : ${BLUE}${BOLD}$COUNT_INFO${NC}"
    echo ""
    echo -e "  ${WHITE}Reports:${NC}"
    [ -f "$OUTPUT_DIR/${REPORT_FILENAME}.txt"  ] && echo -e "   📄 TXT  → $OUTPUT_DIR/${REPORT_FILENAME}.txt"
    [ -f "$OUTPUT_DIR/${REPORT_FILENAME}.html" ] && echo -e "   🌐 HTML → $OUTPUT_DIR/${REPORT_FILENAME}.html"
    [ -f "$OUTPUT_DIR/${REPORT_FILENAME}.pdf"  ] && echo -e "   📑 PDF  → $OUTPUT_DIR/${REPORT_FILENAME}.pdf"
    [ -f "$OUTPUT_DIR/${REPORT_FILENAME}.json" ] && echo -e "   📋 JSON → $OUTPUT_DIR/${REPORT_FILENAME}.json"
    echo ""
    echo -e "${CYAN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

generate_report() {
    local target="$1"
    show_stage 9 "REPORTING"

    generate_txt_report "$target"

    case "$REPORT_FORMAT" in
        2|3)  generate_html_report "$target" ;;
    esac
    case "$REPORT_FORMAT" in
        3)    generate_pdf_report  "$target" ;;
    esac
    case "$OUTPUT_FORMAT" in
        2|3|4) generate_json_report "$target" ;;
    esac

    save_to_sqlite
    show_terminal_dashboard
}
